services:

  postgres-test:
    image: pgvector/pgvector:pg17
    container_name: auction-postgres-test
    environment:
      POSTGRES_DB: auction_test
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.6.2
    container_name: auction-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

