spring:
  config:
    import: aws-parameterstore:/param/reverse-auction/prod/

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    defer-datasource-initialization: false

  cloud:
    # AWS 관련
    aws:
      # parameterstore 활성화
      parameterstore:
        enabled: true
      region:
        static: ap-northeast-2

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

# actuator 관련
management:
  endpoints:
    web:
      exposure:
        include:
          - health

  endpoint:
    health:
      show-details: never
