CREATE EXTENSION IF NOT EXISTS vector;

create table auction_results (
    id bigint generated by default as identity,

    price numeric(38,2) not null,
    auction_id bigint not null,
    buyer_id bigint not null,
    seller_id bigint not null,
    bid_id bigint not null,
    created_at timestamp(6),
    modified_at timestamp(6),

    primary key (id)
);

create table auctions (
    id bigint generated by default as identity,

    user_id bigint not null,
    description varchar(1024),
    max_price numeric(38,2) not null,
    item_name varchar(256) not null,
    auction_status varchar(255) not null check ((auction_status in ('READY','ACTIVE','DONE','NO_BID','CANCELLED'))),
    started_at timestamp(6) not null,
    ended_at timestamp(6) not null,
    cancelled_at timestamp(6),
    category_id bigint not null,
    created_at timestamp(6),

    primary key (id)
);

create table bids (
    id bigint generated by default as identity,

    description varchar(1024),
    price numeric(38,2) not null,
    auction_id bigint not null,
    user_id bigint not null,
    status varchar(255) not null check ((status in ('ACTIVE','CLOSED','CANCELLED'))),
    created_at timestamp(6),

    primary key (id)
);

create table categories (
    id bigint generated by default as identity,

    parent_id bigint,
    name varchar(255) not null,
    depth integer not null,
    created_at timestamp(6),
    modified_at timestamp(6),

    primary key (id),
    unique (parent_id, name)
);

create table chat_messages (
    id bigint generated by default as identity,

    content TEXT not null,
    role varchar(255) not null check ((role in ('USER','ASSISTANT'))),
    room_id bigint not null,
    created_at timestamp(6),

    primary key (id)
);

create table chat_rooms (
    id bigint generated by default as identity,

    title varchar(255),
    user_id bigint not null,
    created_at timestamp(6),

    primary key (id)
);

create table reviews (
    id bigint generated by default as identity,

    auction_id bigint not null,
    reviewer_id bigint not null,
    reviewee_id bigint not null,
    score integer not null check (score between 1 and 5),
    description varchar(500),
    image_url varchar(512),
    created_at timestamp(6),
    modified_at timestamp(6),

    primary key (id),
    unique (auction_id, reviewer_id)
);

create table user_social_accounts (
    id bigint generated by default as identity,

    user_id bigint not null,
    provider varchar(255) not null check ((provider in ('GOOGLE','KAKAO','NAVER'))),
    provider_id varchar(255) not null,

    primary key (id),
    unique (user_id, provider),
    unique (provider, provider_id)
);

create table users (
    id bigint generated by default as identity,

    email varchar(255) not null unique,
    password varchar(255),
    role varchar(255) not null check ((role in ('ADMIN','USER'))),
    rating numeric(2,1),
    created_at timestamp(6),
    modified_at timestamp(6),
    deleted_at timestamp(6),
    deleted boolean not null,

    primary key (id)
);
