create table user_chat_rooms (
    id         bigint generated by default as identity,

    buyer_id   bigint not null,
    seller_id  bigint not null,
    auction_id bigint not null,
    created_at timestamp(6),

    primary key (id),
    unique (buyer_id, seller_id, auction_id)
);

create table user_chat_messages (
    id         bigint generated by default as identity,

    room_id    bigint not null,
    sender_id  bigint not null,
    content    TEXT   not null,

    created_at timestamp(6),
    primary key (id)
);


---------------------------
-- user_chat_rooms FK
---------------------------

alter table user_chat_rooms
    add constraint fk_user_chat_rooms_buyer_id
    foreign key (buyer_id)
    REFERENCES users (id);

alter table user_chat_rooms
    add constraint fk_user_chat_rooms_seller_id
    foreign key (seller_id)
    REFERENCES users (id);

alter table user_chat_rooms
    add constraint fk_user_chat_rooms_auction_id
    foreign key (auction_id)
    REFERENCES auctions (id);

---------------------------
-- user_chat_messages FK
---------------------------

alter table user_chat_messages
    add constraint fk_user_chat_messages_room_id
    foreign key (room_id)
    REFERENCES user_chat_rooms (id);

alter table user_chat_messages
    add constraint fk_user_chat_messages_sender_id
    foreign key (sender_id)
    REFERENCES users (id);
