--    경매 생성 후 EventBridge 스케줄 등록 실패 시 재시도를 위한 outbox 패턴 적용
CREATE TABLE auction_schedule_outbox (
                                         id            bigint generated by default as identity,
                                         auction_id    bigint       not null,
                                         event_type    varchar(255) not null check ((event_type in ('START', 'END'))),
                                         scheduled_at  timestamp(6) not null,
                                         status        varchar(255) not null default 'PENDING'
                                             check ((status in ('PENDING', 'PUBLISHED', 'FAILED'))),
                                         attempt_count int          not null default 0,
                                         last_attempted_at timestamp(6),
                                         created_at    timestamp(6),

                                         primary key (id)
);

CREATE INDEX idx_outbox_status ON auction_schedule_outbox (status);
CREATE INDEX idx_outbox_auction_id ON auction_schedule_outbox (auction_id);