create table auction_document_reindex_jobs (
    id bigint generated by default as identity,

    new_index_name varchar(256),
    job_status varchar(256) not null check ((job_status in ('IN_PROGRESS','FAILED','DONE'))),

    created_at timestamp(6),

    auction_id_cursor bigint not null,

    primary key (id)
);
